packages:
  - "apps/*"
  - "packages/*"

catalogs:
  default:
    typescript: "5.9.3"
    prettier: "^3.8.1"
    eslint: "^9.39.2"
    "@types/node": "^22.19.7"
    react: "^19.2.4"
    react-dom: "^19.2.4"
    "@tanstack/devtools-vite": "^0.6.0"
    "@tanstack/react-devtools": "^0.10.3"
    "@tanstack/react-form": "^1.32.0"
    "@tanstack/react-query": "^5.100.10"
    "@tanstack/react-router": "^1.169.2"
    "@tanstack/react-router-devtools": "^1.166.13"
    "@tanstack/react-store": "^0.11.0"
    "@tanstack/router-plugin": "^1.167.35"
