/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppSearchIndexRouteImport } from './routes/app/search/index'
import { Route as AppNewIndexRouteImport } from './routes/app/new/index'
import { Route as AppLibraryOverviewIndexRouteImport } from './routes/app/library/overview/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchIndexRoute = AppSearchIndexRouteImport.update({
  id: '/app/search/',
  path: '/app/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNewIndexRoute = AppNewIndexRouteImport.update({
  id: '/app/new/',
  path: '/app/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLibraryOverviewIndexRoute = AppLibraryOverviewIndexRouteImport.update({
  id: '/app/library/overview/',
  path: '/app/library/overview/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/new/': typeof AppNewIndexRoute
  '/app/search/': typeof AppSearchIndexRoute
  '/app/library/overview/': typeof AppLibraryOverviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app': typeof AppIndexRoute
  '/app/new': typeof AppNewIndexRoute
  '/app/search': typeof AppSearchIndexRoute
  '/app/library/overview': typeof AppLibraryOverviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/new/': typeof AppNewIndexRoute
  '/app/search/': typeof AppSearchIndexRoute
  '/app/library/overview/': typeof AppLibraryOverviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/new/'
    | '/app/search/'
    | '/app/library/overview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/app'
    | '/app/new'
    | '/app/search'
    | '/app/library/overview'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/new/'
    | '/app/search/'
    | '/app/library/overview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AppIndexRoute: typeof AppIndexRoute
  AppNewIndexRoute: typeof AppNewIndexRoute
  AppSearchIndexRoute: typeof AppSearchIndexRoute
  AppLibraryOverviewIndexRoute: typeof AppLibraryOverviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/search/': {
      id: '/app/search/'
      path: '/app/search'
      fullPath: '/app/search/'
      preLoaderRoute: typeof AppSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/new/': {
      id: '/app/new/'
      path: '/app/new'
      fullPath: '/app/new/'
      preLoaderRoute: typeof AppNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/library/overview/': {
      id: '/app/library/overview/'
      path: '/app/library/overview'
      fullPath: '/app/library/overview/'
      preLoaderRoute: typeof AppLibraryOverviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AppIndexRoute: AppIndexRoute,
  AppNewIndexRoute: AppNewIndexRoute,
  AppSearchIndexRoute: AppSearchIndexRoute,
  AppLibraryOverviewIndexRoute: AppLibraryOverviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
