/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppSearchIndexRouteImport } from './routes/app/search/index'
import { Route as AppNewIndexRouteImport } from './routes/app/new/index'
import { Route as AppLibraryOverviewRouteImport } from './routes/app/library/overview'
import { Route as AppLibraryArtistsRouteImport } from './routes/app/library/artists'
import { Route as AppLibraryOverviewIndexRouteImport } from './routes/app/library/overview/index'
import { Route as AppLibraryArtistsIndexRouteImport } from './routes/app/library/artists/index'
import { Route as AppLibraryOverviewPublicRouteImport } from './routes/app/library/overview/public'
import { Route as AppLibraryOverviewPrivateRouteImport } from './routes/app/library/overview/private'
import { Route as AppLibraryOverviewCommunityRouteImport } from './routes/app/library/overview/community'
import { Route as AppLibraryArtistsCreateRouteImport } from './routes/app/library/artists/create'
import { Route as AppLibraryArtistsIdIndexRouteImport } from './routes/app/library/artists/$id/index'
import { Route as AppLibraryArtistsIdEditRouteImport } from './routes/app/library/artists/$id/edit'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchIndexRoute = AppSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AppRoute,
} as any)
const AppNewIndexRoute = AppNewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryOverviewRoute = AppLibraryOverviewRouteImport.update({
  id: '/library/overview',
  path: '/library/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryArtistsRoute = AppLibraryArtistsRouteImport.update({
  id: '/library/artists',
  path: '/library/artists',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryOverviewIndexRoute = AppLibraryOverviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLibraryOverviewRoute,
} as any)
const AppLibraryArtistsIndexRoute = AppLibraryArtistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLibraryArtistsRoute,
} as any)
const AppLibraryOverviewPublicRoute =
  AppLibraryOverviewPublicRouteImport.update({
    id: '/public',
    path: '/public',
    getParentRoute: () => AppLibraryOverviewRoute,
  } as any)
const AppLibraryOverviewPrivateRoute =
  AppLibraryOverviewPrivateRouteImport.update({
    id: '/private',
    path: '/private',
    getParentRoute: () => AppLibraryOverviewRoute,
  } as any)
const AppLibraryOverviewCommunityRoute =
  AppLibraryOverviewCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AppLibraryOverviewRoute,
  } as any)
const AppLibraryArtistsCreateRoute = AppLibraryArtistsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppLibraryArtistsRoute,
} as any)
const AppLibraryArtistsIdIndexRoute =
  AppLibraryArtistsIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => AppLibraryArtistsRoute,
  } as any)
const AppLibraryArtistsIdEditRoute = AppLibraryArtistsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AppLibraryArtistsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/library/artists': typeof AppLibraryArtistsRouteWithChildren
  '/app/library/overview': typeof AppLibraryOverviewRouteWithChildren
  '/app/new/': typeof AppNewIndexRoute
  '/app/search/': typeof AppSearchIndexRoute
  '/app/library/artists/create': typeof AppLibraryArtistsCreateRoute
  '/app/library/overview/community': typeof AppLibraryOverviewCommunityRoute
  '/app/library/overview/private': typeof AppLibraryOverviewPrivateRoute
  '/app/library/overview/public': typeof AppLibraryOverviewPublicRoute
  '/app/library/artists/': typeof AppLibraryArtistsIndexRoute
  '/app/library/overview/': typeof AppLibraryOverviewIndexRoute
  '/app/library/artists/$id/edit': typeof AppLibraryArtistsIdEditRoute
  '/app/library/artists/$id/': typeof AppLibraryArtistsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app': typeof AppIndexRoute
  '/app/new': typeof AppNewIndexRoute
  '/app/search': typeof AppSearchIndexRoute
  '/app/library/artists/create': typeof AppLibraryArtistsCreateRoute
  '/app/library/overview/community': typeof AppLibraryOverviewCommunityRoute
  '/app/library/overview/private': typeof AppLibraryOverviewPrivateRoute
  '/app/library/overview/public': typeof AppLibraryOverviewPublicRoute
  '/app/library/artists': typeof AppLibraryArtistsIndexRoute
  '/app/library/overview': typeof AppLibraryOverviewIndexRoute
  '/app/library/artists/$id/edit': typeof AppLibraryArtistsIdEditRoute
  '/app/library/artists/$id': typeof AppLibraryArtistsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/library/artists': typeof AppLibraryArtistsRouteWithChildren
  '/app/library/overview': typeof AppLibraryOverviewRouteWithChildren
  '/app/new/': typeof AppNewIndexRoute
  '/app/search/': typeof AppSearchIndexRoute
  '/app/library/artists/create': typeof AppLibraryArtistsCreateRoute
  '/app/library/overview/community': typeof AppLibraryOverviewCommunityRoute
  '/app/library/overview/private': typeof AppLibraryOverviewPrivateRoute
  '/app/library/overview/public': typeof AppLibraryOverviewPublicRoute
  '/app/library/artists/': typeof AppLibraryArtistsIndexRoute
  '/app/library/overview/': typeof AppLibraryOverviewIndexRoute
  '/app/library/artists/$id/edit': typeof AppLibraryArtistsIdEditRoute
  '/app/library/artists/$id/': typeof AppLibraryArtistsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/library/artists'
    | '/app/library/overview'
    | '/app/new/'
    | '/app/search/'
    | '/app/library/artists/create'
    | '/app/library/overview/community'
    | '/app/library/overview/private'
    | '/app/library/overview/public'
    | '/app/library/artists/'
    | '/app/library/overview/'
    | '/app/library/artists/$id/edit'
    | '/app/library/artists/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/app'
    | '/app/new'
    | '/app/search'
    | '/app/library/artists/create'
    | '/app/library/overview/community'
    | '/app/library/overview/private'
    | '/app/library/overview/public'
    | '/app/library/artists'
    | '/app/library/overview'
    | '/app/library/artists/$id/edit'
    | '/app/library/artists/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/library/artists'
    | '/app/library/overview'
    | '/app/new/'
    | '/app/search/'
    | '/app/library/artists/create'
    | '/app/library/overview/community'
    | '/app/library/overview/private'
    | '/app/library/overview/public'
    | '/app/library/artists/'
    | '/app/library/overview/'
    | '/app/library/artists/$id/edit'
    | '/app/library/artists/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/search/': {
      id: '/app/search/'
      path: '/search'
      fullPath: '/app/search/'
      preLoaderRoute: typeof AppSearchIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new/': {
      id: '/app/new/'
      path: '/new'
      fullPath: '/app/new/'
      preLoaderRoute: typeof AppNewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library/overview': {
      id: '/app/library/overview'
      path: '/library/overview'
      fullPath: '/app/library/overview'
      preLoaderRoute: typeof AppLibraryOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library/artists': {
      id: '/app/library/artists'
      path: '/library/artists'
      fullPath: '/app/library/artists'
      preLoaderRoute: typeof AppLibraryArtistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library/overview/': {
      id: '/app/library/overview/'
      path: '/'
      fullPath: '/app/library/overview/'
      preLoaderRoute: typeof AppLibraryOverviewIndexRouteImport
      parentRoute: typeof AppLibraryOverviewRoute
    }
    '/app/library/artists/': {
      id: '/app/library/artists/'
      path: '/'
      fullPath: '/app/library/artists/'
      preLoaderRoute: typeof AppLibraryArtistsIndexRouteImport
      parentRoute: typeof AppLibraryArtistsRoute
    }
    '/app/library/overview/public': {
      id: '/app/library/overview/public'
      path: '/public'
      fullPath: '/app/library/overview/public'
      preLoaderRoute: typeof AppLibraryOverviewPublicRouteImport
      parentRoute: typeof AppLibraryOverviewRoute
    }
    '/app/library/overview/private': {
      id: '/app/library/overview/private'
      path: '/private'
      fullPath: '/app/library/overview/private'
      preLoaderRoute: typeof AppLibraryOverviewPrivateRouteImport
      parentRoute: typeof AppLibraryOverviewRoute
    }
    '/app/library/overview/community': {
      id: '/app/library/overview/community'
      path: '/community'
      fullPath: '/app/library/overview/community'
      preLoaderRoute: typeof AppLibraryOverviewCommunityRouteImport
      parentRoute: typeof AppLibraryOverviewRoute
    }
    '/app/library/artists/create': {
      id: '/app/library/artists/create'
      path: '/create'
      fullPath: '/app/library/artists/create'
      preLoaderRoute: typeof AppLibraryArtistsCreateRouteImport
      parentRoute: typeof AppLibraryArtistsRoute
    }
    '/app/library/artists/$id/': {
      id: '/app/library/artists/$id/'
      path: '/$id'
      fullPath: '/app/library/artists/$id/'
      preLoaderRoute: typeof AppLibraryArtistsIdIndexRouteImport
      parentRoute: typeof AppLibraryArtistsRoute
    }
    '/app/library/artists/$id/edit': {
      id: '/app/library/artists/$id/edit'
      path: '/$id/edit'
      fullPath: '/app/library/artists/$id/edit'
      preLoaderRoute: typeof AppLibraryArtistsIdEditRouteImport
      parentRoute: typeof AppLibraryArtistsRoute
    }
  }
}

interface AppLibraryArtistsRouteChildren {
  AppLibraryArtistsCreateRoute: typeof AppLibraryArtistsCreateRoute
  AppLibraryArtistsIndexRoute: typeof AppLibraryArtistsIndexRoute
  AppLibraryArtistsIdEditRoute: typeof AppLibraryArtistsIdEditRoute
  AppLibraryArtistsIdIndexRoute: typeof AppLibraryArtistsIdIndexRoute
}

const AppLibraryArtistsRouteChildren: AppLibraryArtistsRouteChildren = {
  AppLibraryArtistsCreateRoute: AppLibraryArtistsCreateRoute,
  AppLibraryArtistsIndexRoute: AppLibraryArtistsIndexRoute,
  AppLibraryArtistsIdEditRoute: AppLibraryArtistsIdEditRoute,
  AppLibraryArtistsIdIndexRoute: AppLibraryArtistsIdIndexRoute,
}

const AppLibraryArtistsRouteWithChildren =
  AppLibraryArtistsRoute._addFileChildren(AppLibraryArtistsRouteChildren)

interface AppLibraryOverviewRouteChildren {
  AppLibraryOverviewCommunityRoute: typeof AppLibraryOverviewCommunityRoute
  AppLibraryOverviewPrivateRoute: typeof AppLibraryOverviewPrivateRoute
  AppLibraryOverviewPublicRoute: typeof AppLibraryOverviewPublicRoute
  AppLibraryOverviewIndexRoute: typeof AppLibraryOverviewIndexRoute
}

const AppLibraryOverviewRouteChildren: AppLibraryOverviewRouteChildren = {
  AppLibraryOverviewCommunityRoute: AppLibraryOverviewCommunityRoute,
  AppLibraryOverviewPrivateRoute: AppLibraryOverviewPrivateRoute,
  AppLibraryOverviewPublicRoute: AppLibraryOverviewPublicRoute,
  AppLibraryOverviewIndexRoute: AppLibraryOverviewIndexRoute,
}

const AppLibraryOverviewRouteWithChildren =
  AppLibraryOverviewRoute._addFileChildren(AppLibraryOverviewRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppLibraryArtistsRoute: typeof AppLibraryArtistsRouteWithChildren
  AppLibraryOverviewRoute: typeof AppLibraryOverviewRouteWithChildren
  AppNewIndexRoute: typeof AppNewIndexRoute
  AppSearchIndexRoute: typeof AppSearchIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppLibraryArtistsRoute: AppLibraryArtistsRouteWithChildren,
  AppLibraryOverviewRoute: AppLibraryOverviewRouteWithChildren,
  AppNewIndexRoute: AppNewIndexRoute,
  AppSearchIndexRoute: AppSearchIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
