/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppSearchIndexRouteImport } from './routes/app/search/index'
import { Route as AppNewIndexRouteImport } from './routes/app/new/index'
import { Route as AppLibraryOverviewRouteImport } from './routes/app/library/overview'
import { Route as AppLibraryArtistsRouteImport } from './routes/app/library/artists'
import { Route as AppLibraryAlbumsRouteImport } from './routes/app/library/albums'
import { Route as AppLibraryOverviewIndexRouteImport } from './routes/app/library/overview/index'
import { Route as AppLibraryArtistsIndexRouteImport } from './routes/app/library/artists/index'
import { Route as AppLibraryAlbumsIndexRouteImport } from './routes/app/library/albums/index'
import { Route as AppLibraryOverviewPublicRouteImport } from './routes/app/library/overview/public'
import { Route as AppLibraryOverviewPrivateRouteImport } from './routes/app/library/overview/private'
import { Route as AppLibraryOverviewCommunityRouteImport } from './routes/app/library/overview/community'
import { Route as AppLibraryArtistsCreateRouteImport } from './routes/app/library/artists/create'
import { Route as AppLibraryAlbumsCreateRouteImport } from './routes/app/library/albums/create'
import { Route as AppLibraryAlbumsBulkCreateRouteImport } from './routes/app/library/albums/bulk-create'
import { Route as AppLibraryArtistsIdIndexRouteImport } from './routes/app/library/artists/$id/index'
import { Route as AppLibraryAlbumsIdIndexRouteImport } from './routes/app/library/albums/$id/index'
import { Route as AppLibraryArtistsIdEditRouteImport } from './routes/app/library/artists/$id/edit'
import { Route as AppLibraryAlbumsIdEditRouteImport } from './routes/app/library/albums/$id/edit'
import { Route as AppLibraryArtistsIdAddContentIndexRouteImport } from './routes/app/library/artists/$id/add-content/index'
import { Route as AppLibraryAlbumsIdAddContentIndexRouteImport } from './routes/app/library/albums/$id/add-content/index'
import { Route as AppLibraryArtistsIdAddContentSingleRouteImport } from './routes/app/library/artists/$id/add-content/single'
import { Route as AppLibraryArtistsIdAddContentEpRouteImport } from './routes/app/library/artists/$id/add-content/ep'
import { Route as AppLibraryArtistsIdAddContentCompilationRouteImport } from './routes/app/library/artists/$id/add-content/compilation'
import { Route as AppLibraryArtistsIdAddContentAlbumRouteImport } from './routes/app/library/artists/$id/add-content/album'
import { Route as AppLibraryAlbumsIdAddContentBulkRouteImport } from './routes/app/library/albums/$id/add-content/bulk'
import { Route as AppLibraryAlbumsIdSongsSongIdEditRouteImport } from './routes/app/library/albums/$id/songs/$songId/edit'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchIndexRoute = AppSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AppRoute,
} as any)
const AppNewIndexRoute = AppNewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryOverviewRoute = AppLibraryOverviewRouteImport.update({
  id: '/library/overview',
  path: '/library/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryArtistsRoute = AppLibraryArtistsRouteImport.update({
  id: '/library/artists',
  path: '/library/artists',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryAlbumsRoute = AppLibraryAlbumsRouteImport.update({
  id: '/library/albums',
  path: '/library/albums',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryOverviewIndexRoute = AppLibraryOverviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLibraryOverviewRoute,
} as any)
const AppLibraryArtistsIndexRoute = AppLibraryArtistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLibraryArtistsRoute,
} as any)
const AppLibraryAlbumsIndexRoute = AppLibraryAlbumsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLibraryAlbumsRoute,
} as any)
const AppLibraryOverviewPublicRoute =
  AppLibraryOverviewPublicRouteImport.update({
    id: '/public',
    path: '/public',
    getParentRoute: () => AppLibraryOverviewRoute,
  } as any)
const AppLibraryOverviewPrivateRoute =
  AppLibraryOverviewPrivateRouteImport.update({
    id: '/private',
    path: '/private',
    getParentRoute: () => AppLibraryOverviewRoute,
  } as any)
const AppLibraryOverviewCommunityRoute =
  AppLibraryOverviewCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AppLibraryOverviewRoute,
  } as any)
const AppLibraryArtistsCreateRoute = AppLibraryArtistsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppLibraryArtistsRoute,
} as any)
const AppLibraryAlbumsCreateRoute = AppLibraryAlbumsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppLibraryAlbumsRoute,
} as any)
const AppLibraryAlbumsBulkCreateRoute =
  AppLibraryAlbumsBulkCreateRouteImport.update({
    id: '/bulk-create',
    path: '/bulk-create',
    getParentRoute: () => AppLibraryAlbumsRoute,
  } as any)
const AppLibraryArtistsIdIndexRoute =
  AppLibraryArtistsIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => AppLibraryArtistsRoute,
  } as any)
const AppLibraryAlbumsIdIndexRoute = AppLibraryAlbumsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => AppLibraryAlbumsRoute,
} as any)
const AppLibraryArtistsIdEditRoute = AppLibraryArtistsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AppLibraryArtistsRoute,
} as any)
const AppLibraryAlbumsIdEditRoute = AppLibraryAlbumsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AppLibraryAlbumsRoute,
} as any)
const AppLibraryArtistsIdAddContentIndexRoute =
  AppLibraryArtistsIdAddContentIndexRouteImport.update({
    id: '/$id/add-content/',
    path: '/$id/add-content/',
    getParentRoute: () => AppLibraryArtistsRoute,
  } as any)
const AppLibraryAlbumsIdAddContentIndexRoute =
  AppLibraryAlbumsIdAddContentIndexRouteImport.update({
    id: '/$id/add-content/',
    path: '/$id/add-content/',
    getParentRoute: () => AppLibraryAlbumsRoute,
  } as any)
const AppLibraryArtistsIdAddContentSingleRoute =
  AppLibraryArtistsIdAddContentSingleRouteImport.update({
    id: '/$id/add-content/single',
    path: '/$id/add-content/single',
    getParentRoute: () => AppLibraryArtistsRoute,
  } as any)
const AppLibraryArtistsIdAddContentEpRoute =
  AppLibraryArtistsIdAddContentEpRouteImport.update({
    id: '/$id/add-content/ep',
    path: '/$id/add-content/ep',
    getParentRoute: () => AppLibraryArtistsRoute,
  } as any)
const AppLibraryArtistsIdAddContentCompilationRoute =
  AppLibraryArtistsIdAddContentCompilationRouteImport.update({
    id: '/$id/add-content/compilation',
    path: '/$id/add-content/compilation',
    getParentRoute: () => AppLibraryArtistsRoute,
  } as any)
const AppLibraryArtistsIdAddContentAlbumRoute =
  AppLibraryArtistsIdAddContentAlbumRouteImport.update({
    id: '/$id/add-content/album',
    path: '/$id/add-content/album',
    getParentRoute: () => AppLibraryArtistsRoute,
  } as any)
const AppLibraryAlbumsIdAddContentBulkRoute =
  AppLibraryAlbumsIdAddContentBulkRouteImport.update({
    id: '/$id/add-content/bulk',
    path: '/$id/add-content/bulk',
    getParentRoute: () => AppLibraryAlbumsRoute,
  } as any)
const AppLibraryAlbumsIdSongsSongIdEditRoute =
  AppLibraryAlbumsIdSongsSongIdEditRouteImport.update({
    id: '/$id/songs/$songId/edit',
    path: '/$id/songs/$songId/edit',
    getParentRoute: () => AppLibraryAlbumsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/app/': typeof AppIndexRoute
  '/app/library/albums': typeof AppLibraryAlbumsRouteWithChildren
  '/app/library/artists': typeof AppLibraryArtistsRouteWithChildren
  '/app/library/overview': typeof AppLibraryOverviewRouteWithChildren
  '/app/new/': typeof AppNewIndexRoute
  '/app/search/': typeof AppSearchIndexRoute
  '/app/library/albums/bulk-create': typeof AppLibraryAlbumsBulkCreateRoute
  '/app/library/albums/create': typeof AppLibraryAlbumsCreateRoute
  '/app/library/artists/create': typeof AppLibraryArtistsCreateRoute
  '/app/library/overview/community': typeof AppLibraryOverviewCommunityRoute
  '/app/library/overview/private': typeof AppLibraryOverviewPrivateRoute
  '/app/library/overview/public': typeof AppLibraryOverviewPublicRoute
  '/app/library/albums/': typeof AppLibraryAlbumsIndexRoute
  '/app/library/artists/': typeof AppLibraryArtistsIndexRoute
  '/app/library/overview/': typeof AppLibraryOverviewIndexRoute
  '/app/library/albums/$id/edit': typeof AppLibraryAlbumsIdEditRoute
  '/app/library/artists/$id/edit': typeof AppLibraryArtistsIdEditRoute
  '/app/library/albums/$id/': typeof AppLibraryAlbumsIdIndexRoute
  '/app/library/artists/$id/': typeof AppLibraryArtistsIdIndexRoute
  '/app/library/albums/$id/add-content/bulk': typeof AppLibraryAlbumsIdAddContentBulkRoute
  '/app/library/artists/$id/add-content/album': typeof AppLibraryArtistsIdAddContentAlbumRoute
  '/app/library/artists/$id/add-content/compilation': typeof AppLibraryArtistsIdAddContentCompilationRoute
  '/app/library/artists/$id/add-content/ep': typeof AppLibraryArtistsIdAddContentEpRoute
  '/app/library/artists/$id/add-content/single': typeof AppLibraryArtistsIdAddContentSingleRoute
  '/app/library/albums/$id/add-content/': typeof AppLibraryAlbumsIdAddContentIndexRoute
  '/app/library/artists/$id/add-content/': typeof AppLibraryArtistsIdAddContentIndexRoute
  '/app/library/albums/$id/songs/$songId/edit': typeof AppLibraryAlbumsIdSongsSongIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/app': typeof AppIndexRoute
  '/app/new': typeof AppNewIndexRoute
  '/app/search': typeof AppSearchIndexRoute
  '/app/library/albums/bulk-create': typeof AppLibraryAlbumsBulkCreateRoute
  '/app/library/albums/create': typeof AppLibraryAlbumsCreateRoute
  '/app/library/artists/create': typeof AppLibraryArtistsCreateRoute
  '/app/library/overview/community': typeof AppLibraryOverviewCommunityRoute
  '/app/library/overview/private': typeof AppLibraryOverviewPrivateRoute
  '/app/library/overview/public': typeof AppLibraryOverviewPublicRoute
  '/app/library/albums': typeof AppLibraryAlbumsIndexRoute
  '/app/library/artists': typeof AppLibraryArtistsIndexRoute
  '/app/library/overview': typeof AppLibraryOverviewIndexRoute
  '/app/library/albums/$id/edit': typeof AppLibraryAlbumsIdEditRoute
  '/app/library/artists/$id/edit': typeof AppLibraryArtistsIdEditRoute
  '/app/library/albums/$id': typeof AppLibraryAlbumsIdIndexRoute
  '/app/library/artists/$id': typeof AppLibraryArtistsIdIndexRoute
  '/app/library/albums/$id/add-content/bulk': typeof AppLibraryAlbumsIdAddContentBulkRoute
  '/app/library/artists/$id/add-content/album': typeof AppLibraryArtistsIdAddContentAlbumRoute
  '/app/library/artists/$id/add-content/compilation': typeof AppLibraryArtistsIdAddContentCompilationRoute
  '/app/library/artists/$id/add-content/ep': typeof AppLibraryArtistsIdAddContentEpRoute
  '/app/library/artists/$id/add-content/single': typeof AppLibraryArtistsIdAddContentSingleRoute
  '/app/library/albums/$id/add-content': typeof AppLibraryAlbumsIdAddContentIndexRoute
  '/app/library/artists/$id/add-content': typeof AppLibraryArtistsIdAddContentIndexRoute
  '/app/library/albums/$id/songs/$songId/edit': typeof AppLibraryAlbumsIdSongsSongIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/app/': typeof AppIndexRoute
  '/app/library/albums': typeof AppLibraryAlbumsRouteWithChildren
  '/app/library/artists': typeof AppLibraryArtistsRouteWithChildren
  '/app/library/overview': typeof AppLibraryOverviewRouteWithChildren
  '/app/new/': typeof AppNewIndexRoute
  '/app/search/': typeof AppSearchIndexRoute
  '/app/library/albums/bulk-create': typeof AppLibraryAlbumsBulkCreateRoute
  '/app/library/albums/create': typeof AppLibraryAlbumsCreateRoute
  '/app/library/artists/create': typeof AppLibraryArtistsCreateRoute
  '/app/library/overview/community': typeof AppLibraryOverviewCommunityRoute
  '/app/library/overview/private': typeof AppLibraryOverviewPrivateRoute
  '/app/library/overview/public': typeof AppLibraryOverviewPublicRoute
  '/app/library/albums/': typeof AppLibraryAlbumsIndexRoute
  '/app/library/artists/': typeof AppLibraryArtistsIndexRoute
  '/app/library/overview/': typeof AppLibraryOverviewIndexRoute
  '/app/library/albums/$id/edit': typeof AppLibraryAlbumsIdEditRoute
  '/app/library/artists/$id/edit': typeof AppLibraryArtistsIdEditRoute
  '/app/library/albums/$id/': typeof AppLibraryAlbumsIdIndexRoute
  '/app/library/artists/$id/': typeof AppLibraryArtistsIdIndexRoute
  '/app/library/albums/$id/add-content/bulk': typeof AppLibraryAlbumsIdAddContentBulkRoute
  '/app/library/artists/$id/add-content/album': typeof AppLibraryArtistsIdAddContentAlbumRoute
  '/app/library/artists/$id/add-content/compilation': typeof AppLibraryArtistsIdAddContentCompilationRoute
  '/app/library/artists/$id/add-content/ep': typeof AppLibraryArtistsIdAddContentEpRoute
  '/app/library/artists/$id/add-content/single': typeof AppLibraryArtistsIdAddContentSingleRoute
  '/app/library/albums/$id/add-content/': typeof AppLibraryAlbumsIdAddContentIndexRoute
  '/app/library/artists/$id/add-content/': typeof AppLibraryArtistsIdAddContentIndexRoute
  '/app/library/albums/$id/songs/$songId/edit': typeof AppLibraryAlbumsIdSongsSongIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/app/'
    | '/app/library/albums'
    | '/app/library/artists'
    | '/app/library/overview'
    | '/app/new/'
    | '/app/search/'
    | '/app/library/albums/bulk-create'
    | '/app/library/albums/create'
    | '/app/library/artists/create'
    | '/app/library/overview/community'
    | '/app/library/overview/private'
    | '/app/library/overview/public'
    | '/app/library/albums/'
    | '/app/library/artists/'
    | '/app/library/overview/'
    | '/app/library/albums/$id/edit'
    | '/app/library/artists/$id/edit'
    | '/app/library/albums/$id/'
    | '/app/library/artists/$id/'
    | '/app/library/albums/$id/add-content/bulk'
    | '/app/library/artists/$id/add-content/album'
    | '/app/library/artists/$id/add-content/compilation'
    | '/app/library/artists/$id/add-content/ep'
    | '/app/library/artists/$id/add-content/single'
    | '/app/library/albums/$id/add-content/'
    | '/app/library/artists/$id/add-content/'
    | '/app/library/albums/$id/songs/$songId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/app'
    | '/app/new'
    | '/app/search'
    | '/app/library/albums/bulk-create'
    | '/app/library/albums/create'
    | '/app/library/artists/create'
    | '/app/library/overview/community'
    | '/app/library/overview/private'
    | '/app/library/overview/public'
    | '/app/library/albums'
    | '/app/library/artists'
    | '/app/library/overview'
    | '/app/library/albums/$id/edit'
    | '/app/library/artists/$id/edit'
    | '/app/library/albums/$id'
    | '/app/library/artists/$id'
    | '/app/library/albums/$id/add-content/bulk'
    | '/app/library/artists/$id/add-content/album'
    | '/app/library/artists/$id/add-content/compilation'
    | '/app/library/artists/$id/add-content/ep'
    | '/app/library/artists/$id/add-content/single'
    | '/app/library/albums/$id/add-content'
    | '/app/library/artists/$id/add-content'
    | '/app/library/albums/$id/songs/$songId/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/app/'
    | '/app/library/albums'
    | '/app/library/artists'
    | '/app/library/overview'
    | '/app/new/'
    | '/app/search/'
    | '/app/library/albums/bulk-create'
    | '/app/library/albums/create'
    | '/app/library/artists/create'
    | '/app/library/overview/community'
    | '/app/library/overview/private'
    | '/app/library/overview/public'
    | '/app/library/albums/'
    | '/app/library/artists/'
    | '/app/library/overview/'
    | '/app/library/albums/$id/edit'
    | '/app/library/artists/$id/edit'
    | '/app/library/albums/$id/'
    | '/app/library/artists/$id/'
    | '/app/library/albums/$id/add-content/bulk'
    | '/app/library/artists/$id/add-content/album'
    | '/app/library/artists/$id/add-content/compilation'
    | '/app/library/artists/$id/add-content/ep'
    | '/app/library/artists/$id/add-content/single'
    | '/app/library/albums/$id/add-content/'
    | '/app/library/artists/$id/add-content/'
    | '/app/library/albums/$id/songs/$songId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/search/': {
      id: '/app/search/'
      path: '/search'
      fullPath: '/app/search/'
      preLoaderRoute: typeof AppSearchIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new/': {
      id: '/app/new/'
      path: '/new'
      fullPath: '/app/new/'
      preLoaderRoute: typeof AppNewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library/overview': {
      id: '/app/library/overview'
      path: '/library/overview'
      fullPath: '/app/library/overview'
      preLoaderRoute: typeof AppLibraryOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library/artists': {
      id: '/app/library/artists'
      path: '/library/artists'
      fullPath: '/app/library/artists'
      preLoaderRoute: typeof AppLibraryArtistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library/albums': {
      id: '/app/library/albums'
      path: '/library/albums'
      fullPath: '/app/library/albums'
      preLoaderRoute: typeof AppLibraryAlbumsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library/overview/': {
      id: '/app/library/overview/'
      path: '/'
      fullPath: '/app/library/overview/'
      preLoaderRoute: typeof AppLibraryOverviewIndexRouteImport
      parentRoute: typeof AppLibraryOverviewRoute
    }
    '/app/library/artists/': {
      id: '/app/library/artists/'
      path: '/'
      fullPath: '/app/library/artists/'
      preLoaderRoute: typeof AppLibraryArtistsIndexRouteImport
      parentRoute: typeof AppLibraryArtistsRoute
    }
    '/app/library/albums/': {
      id: '/app/library/albums/'
      path: '/'
      fullPath: '/app/library/albums/'
      preLoaderRoute: typeof AppLibraryAlbumsIndexRouteImport
      parentRoute: typeof AppLibraryAlbumsRoute
    }
    '/app/library/overview/public': {
      id: '/app/library/overview/public'
      path: '/public'
      fullPath: '/app/library/overview/public'
      preLoaderRoute: typeof AppLibraryOverviewPublicRouteImport
      parentRoute: typeof AppLibraryOverviewRoute
    }
    '/app/library/overview/private': {
      id: '/app/library/overview/private'
      path: '/private'
      fullPath: '/app/library/overview/private'
      preLoaderRoute: typeof AppLibraryOverviewPrivateRouteImport
      parentRoute: typeof AppLibraryOverviewRoute
    }
    '/app/library/overview/community': {
      id: '/app/library/overview/community'
      path: '/community'
      fullPath: '/app/library/overview/community'
      preLoaderRoute: typeof AppLibraryOverviewCommunityRouteImport
      parentRoute: typeof AppLibraryOverviewRoute
    }
    '/app/library/artists/create': {
      id: '/app/library/artists/create'
      path: '/create'
      fullPath: '/app/library/artists/create'
      preLoaderRoute: typeof AppLibraryArtistsCreateRouteImport
      parentRoute: typeof AppLibraryArtistsRoute
    }
    '/app/library/albums/create': {
      id: '/app/library/albums/create'
      path: '/create'
      fullPath: '/app/library/albums/create'
      preLoaderRoute: typeof AppLibraryAlbumsCreateRouteImport
      parentRoute: typeof AppLibraryAlbumsRoute
    }
    '/app/library/albums/bulk-create': {
      id: '/app/library/albums/bulk-create'
      path: '/bulk-create'
      fullPath: '/app/library/albums/bulk-create'
      preLoaderRoute: typeof AppLibraryAlbumsBulkCreateRouteImport
      parentRoute: typeof AppLibraryAlbumsRoute
    }
    '/app/library/artists/$id/': {
      id: '/app/library/artists/$id/'
      path: '/$id'
      fullPath: '/app/library/artists/$id/'
      preLoaderRoute: typeof AppLibraryArtistsIdIndexRouteImport
      parentRoute: typeof AppLibraryArtistsRoute
    }
    '/app/library/albums/$id/': {
      id: '/app/library/albums/$id/'
      path: '/$id'
      fullPath: '/app/library/albums/$id/'
      preLoaderRoute: typeof AppLibraryAlbumsIdIndexRouteImport
      parentRoute: typeof AppLibraryAlbumsRoute
    }
    '/app/library/artists/$id/edit': {
      id: '/app/library/artists/$id/edit'
      path: '/$id/edit'
      fullPath: '/app/library/artists/$id/edit'
      preLoaderRoute: typeof AppLibraryArtistsIdEditRouteImport
      parentRoute: typeof AppLibraryArtistsRoute
    }
    '/app/library/albums/$id/edit': {
      id: '/app/library/albums/$id/edit'
      path: '/$id/edit'
      fullPath: '/app/library/albums/$id/edit'
      preLoaderRoute: typeof AppLibraryAlbumsIdEditRouteImport
      parentRoute: typeof AppLibraryAlbumsRoute
    }
    '/app/library/artists/$id/add-content/': {
      id: '/app/library/artists/$id/add-content/'
      path: '/$id/add-content'
      fullPath: '/app/library/artists/$id/add-content/'
      preLoaderRoute: typeof AppLibraryArtistsIdAddContentIndexRouteImport
      parentRoute: typeof AppLibraryArtistsRoute
    }
    '/app/library/albums/$id/add-content/': {
      id: '/app/library/albums/$id/add-content/'
      path: '/$id/add-content'
      fullPath: '/app/library/albums/$id/add-content/'
      preLoaderRoute: typeof AppLibraryAlbumsIdAddContentIndexRouteImport
      parentRoute: typeof AppLibraryAlbumsRoute
    }
    '/app/library/artists/$id/add-content/single': {
      id: '/app/library/artists/$id/add-content/single'
      path: '/$id/add-content/single'
      fullPath: '/app/library/artists/$id/add-content/single'
      preLoaderRoute: typeof AppLibraryArtistsIdAddContentSingleRouteImport
      parentRoute: typeof AppLibraryArtistsRoute
    }
    '/app/library/artists/$id/add-content/ep': {
      id: '/app/library/artists/$id/add-content/ep'
      path: '/$id/add-content/ep'
      fullPath: '/app/library/artists/$id/add-content/ep'
      preLoaderRoute: typeof AppLibraryArtistsIdAddContentEpRouteImport
      parentRoute: typeof AppLibraryArtistsRoute
    }
    '/app/library/artists/$id/add-content/compilation': {
      id: '/app/library/artists/$id/add-content/compilation'
      path: '/$id/add-content/compilation'
      fullPath: '/app/library/artists/$id/add-content/compilation'
      preLoaderRoute: typeof AppLibraryArtistsIdAddContentCompilationRouteImport
      parentRoute: typeof AppLibraryArtistsRoute
    }
    '/app/library/artists/$id/add-content/album': {
      id: '/app/library/artists/$id/add-content/album'
      path: '/$id/add-content/album'
      fullPath: '/app/library/artists/$id/add-content/album'
      preLoaderRoute: typeof AppLibraryArtistsIdAddContentAlbumRouteImport
      parentRoute: typeof AppLibraryArtistsRoute
    }
    '/app/library/albums/$id/add-content/bulk': {
      id: '/app/library/albums/$id/add-content/bulk'
      path: '/$id/add-content/bulk'
      fullPath: '/app/library/albums/$id/add-content/bulk'
      preLoaderRoute: typeof AppLibraryAlbumsIdAddContentBulkRouteImport
      parentRoute: typeof AppLibraryAlbumsRoute
    }
    '/app/library/albums/$id/songs/$songId/edit': {
      id: '/app/library/albums/$id/songs/$songId/edit'
      path: '/$id/songs/$songId/edit'
      fullPath: '/app/library/albums/$id/songs/$songId/edit'
      preLoaderRoute: typeof AppLibraryAlbumsIdSongsSongIdEditRouteImport
      parentRoute: typeof AppLibraryAlbumsRoute
    }
  }
}

interface AppLibraryAlbumsRouteChildren {
  AppLibraryAlbumsBulkCreateRoute: typeof AppLibraryAlbumsBulkCreateRoute
  AppLibraryAlbumsCreateRoute: typeof AppLibraryAlbumsCreateRoute
  AppLibraryAlbumsIndexRoute: typeof AppLibraryAlbumsIndexRoute
  AppLibraryAlbumsIdEditRoute: typeof AppLibraryAlbumsIdEditRoute
  AppLibraryAlbumsIdIndexRoute: typeof AppLibraryAlbumsIdIndexRoute
  AppLibraryAlbumsIdAddContentBulkRoute: typeof AppLibraryAlbumsIdAddContentBulkRoute
  AppLibraryAlbumsIdAddContentIndexRoute: typeof AppLibraryAlbumsIdAddContentIndexRoute
  AppLibraryAlbumsIdSongsSongIdEditRoute: typeof AppLibraryAlbumsIdSongsSongIdEditRoute
}

const AppLibraryAlbumsRouteChildren: AppLibraryAlbumsRouteChildren = {
  AppLibraryAlbumsBulkCreateRoute: AppLibraryAlbumsBulkCreateRoute,
  AppLibraryAlbumsCreateRoute: AppLibraryAlbumsCreateRoute,
  AppLibraryAlbumsIndexRoute: AppLibraryAlbumsIndexRoute,
  AppLibraryAlbumsIdEditRoute: AppLibraryAlbumsIdEditRoute,
  AppLibraryAlbumsIdIndexRoute: AppLibraryAlbumsIdIndexRoute,
  AppLibraryAlbumsIdAddContentBulkRoute: AppLibraryAlbumsIdAddContentBulkRoute,
  AppLibraryAlbumsIdAddContentIndexRoute:
    AppLibraryAlbumsIdAddContentIndexRoute,
  AppLibraryAlbumsIdSongsSongIdEditRoute:
    AppLibraryAlbumsIdSongsSongIdEditRoute,
}

const AppLibraryAlbumsRouteWithChildren =
  AppLibraryAlbumsRoute._addFileChildren(AppLibraryAlbumsRouteChildren)

interface AppLibraryArtistsRouteChildren {
  AppLibraryArtistsCreateRoute: typeof AppLibraryArtistsCreateRoute
  AppLibraryArtistsIndexRoute: typeof AppLibraryArtistsIndexRoute
  AppLibraryArtistsIdEditRoute: typeof AppLibraryArtistsIdEditRoute
  AppLibraryArtistsIdIndexRoute: typeof AppLibraryArtistsIdIndexRoute
  AppLibraryArtistsIdAddContentAlbumRoute: typeof AppLibraryArtistsIdAddContentAlbumRoute
  AppLibraryArtistsIdAddContentCompilationRoute: typeof AppLibraryArtistsIdAddContentCompilationRoute
  AppLibraryArtistsIdAddContentEpRoute: typeof AppLibraryArtistsIdAddContentEpRoute
  AppLibraryArtistsIdAddContentSingleRoute: typeof AppLibraryArtistsIdAddContentSingleRoute
  AppLibraryArtistsIdAddContentIndexRoute: typeof AppLibraryArtistsIdAddContentIndexRoute
}

const AppLibraryArtistsRouteChildren: AppLibraryArtistsRouteChildren = {
  AppLibraryArtistsCreateRoute: AppLibraryArtistsCreateRoute,
  AppLibraryArtistsIndexRoute: AppLibraryArtistsIndexRoute,
  AppLibraryArtistsIdEditRoute: AppLibraryArtistsIdEditRoute,
  AppLibraryArtistsIdIndexRoute: AppLibraryArtistsIdIndexRoute,
  AppLibraryArtistsIdAddContentAlbumRoute:
    AppLibraryArtistsIdAddContentAlbumRoute,
  AppLibraryArtistsIdAddContentCompilationRoute:
    AppLibraryArtistsIdAddContentCompilationRoute,
  AppLibraryArtistsIdAddContentEpRoute: AppLibraryArtistsIdAddContentEpRoute,
  AppLibraryArtistsIdAddContentSingleRoute:
    AppLibraryArtistsIdAddContentSingleRoute,
  AppLibraryArtistsIdAddContentIndexRoute:
    AppLibraryArtistsIdAddContentIndexRoute,
}

const AppLibraryArtistsRouteWithChildren =
  AppLibraryArtistsRoute._addFileChildren(AppLibraryArtistsRouteChildren)

interface AppLibraryOverviewRouteChildren {
  AppLibraryOverviewCommunityRoute: typeof AppLibraryOverviewCommunityRoute
  AppLibraryOverviewPrivateRoute: typeof AppLibraryOverviewPrivateRoute
  AppLibraryOverviewPublicRoute: typeof AppLibraryOverviewPublicRoute
  AppLibraryOverviewIndexRoute: typeof AppLibraryOverviewIndexRoute
}

const AppLibraryOverviewRouteChildren: AppLibraryOverviewRouteChildren = {
  AppLibraryOverviewCommunityRoute: AppLibraryOverviewCommunityRoute,
  AppLibraryOverviewPrivateRoute: AppLibraryOverviewPrivateRoute,
  AppLibraryOverviewPublicRoute: AppLibraryOverviewPublicRoute,
  AppLibraryOverviewIndexRoute: AppLibraryOverviewIndexRoute,
}

const AppLibraryOverviewRouteWithChildren =
  AppLibraryOverviewRoute._addFileChildren(AppLibraryOverviewRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppLibraryAlbumsRoute: typeof AppLibraryAlbumsRouteWithChildren
  AppLibraryArtistsRoute: typeof AppLibraryArtistsRouteWithChildren
  AppLibraryOverviewRoute: typeof AppLibraryOverviewRouteWithChildren
  AppNewIndexRoute: typeof AppNewIndexRoute
  AppSearchIndexRoute: typeof AppSearchIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppLibraryAlbumsRoute: AppLibraryAlbumsRouteWithChildren,
  AppLibraryArtistsRoute: AppLibraryArtistsRouteWithChildren,
  AppLibraryOverviewRoute: AppLibraryOverviewRouteWithChildren,
  AppNewIndexRoute: AppNewIndexRoute,
  AppSearchIndexRoute: AppSearchIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
