import type { PlayerState } from '@/stores/player.store';
import { vi } from 'vitest';

export function createPlayerStateMock(overrides: Partial<PlayerState> = {}): PlayerState {
  return {
    currentTrack: null,
    isPlaying: false,
    volume: 1,
    currentTime: 0,
    duration: 0,
    quality: 'auto',
    availableQualities: ['auto'],
    queue: [],
    originalQueue: [],
    history: [],
    repeatMode: 'off',
    isShuffled: false,
    playbackVersion: 0,
    playbackFavorited: 'not-set',
    playbackInLibrary: false,
    activeDeviceId: '',
    localPlaybackDeviceId: '',
    playbackDevices: [],
    applyPlaybackStateFromServer: vi.fn(),
    setLocalPlaybackDeviceId: vi.fn(),
    setPlaybackDevices: vi.fn(),
    playTrack: vi.fn(),
    pause: vi.fn(),
    resume: vi.fn(),
    togglePlay: vi.fn(),
    setVolume: vi.fn(),
    setCurrentTime: vi.fn(),
    setDuration: vi.fn(),
    setQuality: vi.fn(),
    setAvailableQualities: vi.fn(),
    setQueue: vi.fn(),
    nextTrack: vi.fn(),
    previousTrack: vi.fn(),
    toggleRepeatMode: vi.fn(),
    toggleShuffle: vi.fn(),
    addToQueue: vi.fn(),
    playNext: vi.fn(),
    removeFromQueue: vi.fn(),
    reorderQueue: vi.fn(),
    addToHistory: vi.fn(),
    isQueueOpen: false,
    sidebarView: 'queue',
    toggleQueue: vi.fn(),
    setQueueOpen: vi.fn(),
    setSidebarView: vi.fn(),
    ...overrides,
  };
}
